# Generated by Django 3.1.4 on 2021-03-23 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_insurance_contract_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_contract',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=8),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_date', models.DateField()),
                ('familial_contribution', models.BooleanField()),
                ('cash_payment', models.BooleanField()),
                ('transfer_payment', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.member')),
            ],
        ),
    ]
