# Generated by Django 3.1.4 on 2021-03-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20210323_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='race',
        ),
        migrations.AddField(
            model_name='dog',
            name='race',
            field=models.ManyToManyField(related_name='dog_races', to='controller.Race'),
        ),
    ]
